var player;
var player2;
var aliens;
var bullets;
var bullets2;
var bulletTime = 0;
var bulletTime2 = 0;
var cursors;
var fireButton;
var explosions;
var starfield;
var score = 0;
var scoreString = '';
var scoreText;
var lives;
var enemyBullet;
var firingTimer = 0;
var stateText;
var livingEnemies = [];
var dificulty = 50;